package com.qeagent.agents;

import com.fasterxml.jackson.databind.JsonNode;
import com.qeagent.models.Defect;
import com.qeagent.models.TestExecutionResult;
import com.qeagent.models.TestPlan;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Stage 4: Convert failures to actionable defects with LLM-assisted triage.
 */
public class DefectTriageAgent extends BaseAgent {
    private static final Logger logger = LoggerFactory.getLogger(DefectTriageAgent.class);

    public List<Defect> triageResults(List<TestExecutionResult> results, TestPlan testPlan) {
        List<TestExecutionResult> failures = results.stream()
            .filter(r -> TestExecutionResult.ExecutionStatus.FAILED == r.getStatus()
                || TestExecutionResult.ExecutionStatus.ERROR == r.getStatus()
                || TestExecutionResult.ExecutionStatus.TIMEOUT == r.getStatus())
            .collect(Collectors.toList());

        if (failures.isEmpty()) {
            return new ArrayList<>();
        }

        String systemPrompt = """
            You are a QE triage lead.
            Return only JSON with top-level key defects[] where each item includes:
            title, severity, priority, hypothesis, recommendedInvestigation, likelyComponents, confidenceScore.
            Group similar failures and avoid duplicates.
            """;

        String userPrompt = "Test plan risk: " + (testPlan.getRiskAssessment() == null ? "UNKNOWN" : testPlan.getRiskAssessment().getOverallRisk())
            + "\nFailure samples:\n" + toJson(failures.stream().limit(10).collect(Collectors.toList()));

        String raw = invokeLlmOrFallback(
            "DefectTriageAgent",
            systemPrompt,
            userPrompt,
            () -> fallbackTriageJson(failures)
        );

        List<Defect> parsed = parseDefects(raw, failures);
        return deduplicateByNormalizedTitle(parsed);
    }

    private List<Defect> parseDefects(String raw, List<TestExecutionResult> failures) {
        List<Defect> defects = new ArrayList<>();
        try {
            JsonNode root = MAPPER.readTree(raw);
            JsonNode arr = root.path("defects");
            if (!arr.isArray()) {
                return buildFallbackDefects(failures);
            }

            for (JsonNode node : arr) {
                Defect defect = new Defect("DEF-" + UUID.randomUUID().toString().substring(0, 8),
                    node.path("title").asText("Execution failure cluster"),
                    parseSeverity(node.path("severity").asText("HIGH")));

                defect.setPriority(parsePriority(node.path("priority").asText("P1")));
                defect.setStatus(Defect.DefectStatus.NEW);
                defect.setDescription("LLM-triaged defect from execution failures");

                Defect.RootCauseAnalysis rca = new Defect.RootCauseAnalysis();
                rca.setHypothesis(node.path("hypothesis").asText("Potential application defect in failure path"));
                rca.setRecommendedInvestigation(node.path("recommendedInvestigation").asText("Inspect logs and API contract mismatches"));
                rca.setConfidence(node.path("confidenceScore").asDouble(0.7));
                for (JsonNode c : node.path("likelyComponents")) {
                    rca.getLikelyComponents().add(c.asText());
                }
                defect.setRootCauseAnalysis(rca);
                defect.setConfidenceScore(node.path("confidenceScore").asDouble(0.7));
                defect.setTriageNotes("Generated by LLM triage agent");

                for (TestExecutionResult failure : failures) {
                    defect.getTestResultIds().add(failure.getResultId());
                }

                defects.add(defect);
            }
        } catch (Exception ex) {
            logger.error("Defect triage parse failed: {}", ex.getMessage());
            return buildFallbackDefects(failures);
        }

        if (defects.isEmpty()) {
            return buildFallbackDefects(failures);
        }
        return defects;
    }

    private List<Defect> buildFallbackDefects(List<TestExecutionResult> failures) {
        List<Defect> defects = new ArrayList<>();
        for (TestExecutionResult failure : failures) {
            Defect defect = new Defect(
                "DEF-" + UUID.randomUUID().toString().substring(0, 8),
                "Failure in test " + failure.getTestId(),
                Defect.Severity.HIGH
            );
            defect.setPriority(Defect.Priority.P1);
            defect.setStatus(Defect.DefectStatus.NEW);
            defect.setDescription(failure.getErrorMessage() == null ? "Execution failure" : failure.getErrorMessage());
            defect.getTestResultIds().add(failure.getResultId());

            Defect.RootCauseAnalysis rca = new Defect.RootCauseAnalysis();
            rca.setHypothesis("Likely contract/assertion mismatch in tested flow");
            rca.setRecommendedInvestigation("Review failing assertion and payload contract");
            rca.setConfidence(0.6);
            rca.getLikelyComponents().add("Application Service");
            defect.setRootCauseAnalysis(rca);
            defect.setConfidenceScore(0.6);
            defect.setTriageNotes("Fallback triage used due missing/failed LLM response");

            defects.add(defect);
        }
        return defects;
    }

    private List<Defect> deduplicateByNormalizedTitle(List<Defect> defects) {
        Set<String> seen = new HashSet<>();
        List<Defect> deduped = new ArrayList<>();

        for (Defect d : defects) {
            String key = d.getTitle().toLowerCase().replaceAll("\\d+", "X").trim();
            if (seen.add(key)) {
                deduped.add(d);
            }
        }
        return deduped;
    }

    private Defect.Severity parseSeverity(String severity) {
        try {
            return Defect.Severity.valueOf(severity.toUpperCase());
        } catch (Exception ex) {
            return Defect.Severity.HIGH;
        }
    }

    private Defect.Priority parsePriority(String priority) {
        try {
            return Defect.Priority.valueOf(priority.toUpperCase());
        } catch (Exception ex) {
            return Defect.Priority.P1;
        }
    }

    private String toJson(Object value) {
        try {
            return MAPPER.writeValueAsString(value);
        } catch (Exception ex) {
            return "[]";
        }
    }

    private String fallbackTriageJson(List<TestExecutionResult> failures) {
        int count = Math.max(1, failures.size());
        return "{" +
            "\"defects\":[{" +
            "\"title\":\"Execution failure cluster\"," +
            "\"severity\":\"HIGH\"," +
            "\"priority\":\"P1\"," +
            "\"hypothesis\":\"Validation/contract mismatch in failure path\"," +
            "\"recommendedInvestigation\":\"Review failing payload and assertion logs\"," +
            "\"likelyComponents\":[\"API Layer\",\"Validation Layer\"]," +
            "\"confidenceScore\":" + (count > 2 ? "0.8" : "0.7") +
            "}]}";
    }
}
