package com.qeagent.agents;

import com.fasterxml.jackson.databind.JsonNode;
import com.qeagent.models.TestPlan;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

/**
 * Stage 1: Convert artifact into risk-based test plan using LLM.
 */
public class TestPlannerAgent extends BaseAgent {
    private static final Logger logger = LoggerFactory.getLogger(TestPlannerAgent.class);

    public TestPlan generateTestPlan(String artifactContent, TestPlan.ArtifactType type) {
        String planId = "TP-" + UUID.randomUUID().toString().substring(0, 8);
        TestPlan plan = new TestPlan(planId, "Product Artifact", type);

        String systemPrompt = """
            You are a senior QA architect.
            Return only JSON with fields:
            riskAssessment, testScenarios, coverageAreas, ambiguities, testDataRequirements, entryCriteria, exitCriteria, rationale.
            Use high-value risk-based prioritization with meaningful negative and boundary cases.
            """;

        String userPrompt = "Artifact type: " + type + "\nArtifact content:\n" + artifactContent;

        String raw = invokeLlmOrFallback(
            "TestPlannerAgent",
            systemPrompt,
            userPrompt,
            () -> fallbackPlannerJson(artifactContent)
        );

        try {
            JsonNode root = MAPPER.readTree(raw);
            hydrateRisk(plan, root.path("riskAssessment"));
            hydrateScenarios(plan, root.path("testScenarios"));
            hydrateCoverage(plan, root.path("coverageAreas"));
            hydrateDataRequirements(plan, root.path("testDataRequirements"));
            plan.setAmbiguities(readStringList(root.path("ambiguities")));
            plan.setEntryCriteria(readStringList(root.path("entryCriteria")));
            plan.setExitCriteria(readStringList(root.path("exitCriteria")));
            plan.setRationale(root.path("rationale").asText("Risk-based plan generated by LLM"));
        } catch (Exception ex) {
            logger.error("Planner parse failed; falling back to deterministic plan: {}", ex.getMessage());
            return buildFallbackPlan(planId, type, artifactContent);
        }

        logger.info("TestPlannerAgent: generated plan {} with {} scenarios", plan.getPlanId(), plan.getTestScenarios().size());
        return plan;
    }

    private void hydrateRisk(TestPlan plan, JsonNode node) {
        TestPlan.RiskAssessment assessment = new TestPlan.RiskAssessment();
        assessment.setOverallRisk(node.path("overallRisk").asText("HIGH"));
        assessment.setJustification(node.path("justification").asText("Risk profile inferred from artifact"));

        List<TestPlan.RiskArea> areas = new ArrayList<>();
        for (JsonNode area : node.path("riskAreas")) {
            areas.add(new TestPlan.RiskArea(
                area.path("area").asText(area.path("component").asText("Core Functionality")),
                area.path("severity").asText("HIGH"),
                area.path("likelihood").asText("MEDIUM"),
                area.path("description").asText("High-impact behavior"))
            );
        }

        if (areas.isEmpty()) {
            areas.add(new TestPlan.RiskArea("Core Functionality", "HIGH", "HIGH", "Primary business flow"));
        }

        assessment.setRiskAreas(areas);
        plan.setRiskAssessment(assessment);
    }

    private void hydrateScenarios(TestPlan plan, JsonNode scenariosNode) {
        List<TestPlan.TestScenario> scenarios = new ArrayList<>();
        int index = 1;
        for (JsonNode node : scenariosNode) {
            TestPlan.TestScenario s = new TestPlan.TestScenario();
            s.setId(node.path("id").asText("TS-" + index));
            s.setTitle(node.path("title").asText("Scenario " + index));
            s.setDescription(node.path("description").asText("Generated scenario"));
            s.setPriority(node.path("priority").asText("HIGH"));
            s.setType(node.path("type").asText("NEGATIVE"));
            for (String p : readStringList(node.path("preconditions"))) {
                s.getPreconditions().add(p);
            }
            for (String step : readStringList(node.path("steps"))) {
                s.getSteps().add(step);
            }
            s.setExpectedResult(node.path("expectedResult").asText("Expected behavior should match spec"));
            scenarios.add(s);
            index++;
        }

        if (scenarios.isEmpty()) {
            scenarios = buildFallbackPlan(plan.getPlanId(), plan.getArtifactType(), "").getTestScenarios();
        }
        plan.setTestScenarios(scenarios);
    }

    private void hydrateCoverage(TestPlan plan, JsonNode coverageNode) {
        List<TestPlan.CoverageArea> coverageAreas = new ArrayList<>();
        for (JsonNode node : coverageNode) {
            coverageAreas.add(new TestPlan.CoverageArea(
                node.path("area").asText(node.path("name").asText("Functional")),
                node.path("coveragePercent").asDouble(80.0),
                node.path("scenariosCount").asInt(Math.max(1, plan.getTestScenarios().size() / 2))
            ));
        }
        if (coverageAreas.isEmpty()) {
            coverageAreas.add(new TestPlan.CoverageArea("Functional", 85.0, Math.max(1, plan.getTestScenarios().size())));
        }
        plan.setCoverageAreas(coverageAreas);
    }

    private void hydrateDataRequirements(TestPlan plan, JsonNode dataNode) {
        List<TestPlan.TestDataRequirement> reqs = new ArrayList<>();
        for (JsonNode node : dataNode) {
            TestPlan.TestDataRequirement req = new TestPlan.TestDataRequirement(
                node.path("entity").asText(node.path("description").asText("Test Data")),
                node.path("quantity").asInt(3)
            );
            req.getAttributes().put("source", node.path("scenarioId").asText("general"));
            reqs.add(req);
        }

        if (reqs.isEmpty()) {
            reqs.add(new TestPlan.TestDataRequirement("Valid User", 3));
            reqs.add(new TestPlan.TestDataRequirement("Invalid User", 2));
        }
        plan.setTestDataRequirements(reqs);
    }

    private List<String> readStringList(JsonNode node) {
        List<String> values = new ArrayList<>();
        if (node.isArray()) {
            for (JsonNode item : node) {
                values.add(item.asText());
            }
        }
        return values;
    }

    private TestPlan buildFallbackPlan(String planId, TestPlan.ArtifactType type, String artifactContent) {
        TestPlan plan = new TestPlan(planId, "Product Artifact", type);

        TestPlan.RiskAssessment risk = new TestPlan.RiskAssessment();
        risk.setOverallRisk("HIGH");
        risk.setJustification("Fallback deterministic plan used");
        risk.setRiskAreas(Arrays.asList(
            new TestPlan.RiskArea("Core Functionality", "HIGH", "HIGH", "Primary flow validation"),
            new TestPlan.RiskArea("Validation", "HIGH", "MEDIUM", "Input and boundary behavior")
        ));
        plan.setRiskAssessment(risk);

        TestPlan.TestScenario s1 = new TestPlan.TestScenario();
        s1.setId("TS-1");
        s1.setTitle("Happy path workflow");
        s1.setDescription("Core user flow with valid data");
        s1.setPriority("CRITICAL");
        s1.setType("HAPPY_PATH");
        s1.getSteps().add("Execute primary flow with valid payload");
        s1.setExpectedResult("System returns success");

        TestPlan.TestScenario s2 = new TestPlan.TestScenario();
        s2.setId("TS-2");
        s2.setTitle("Boundary and negative behavior");
        s2.setDescription("Invalid values and empty inputs");
        s2.setPriority("HIGH");
        s2.setType("BOUNDARY");
        s2.getSteps().add("Send invalid payload");
        s2.setExpectedResult("Validation errors returned");

        plan.setTestScenarios(Arrays.asList(s1, s2));
        plan.setCoverageAreas(Arrays.asList(
            new TestPlan.CoverageArea("Functional", 85.0, 2),
            new TestPlan.CoverageArea("Validation", 80.0, 1)
        ));
        plan.setEntryCriteria(Arrays.asList("Environment available", "Artifact parsed"));
        plan.setExitCriteria(Arrays.asList("Critical scenarios executed", "No blocker defects"));
        plan.setAmbiguities(Arrays.asList(
            artifactContent.toLowerCase().contains("tbd")
                ? "Artifact includes TBD sections"
                : "Clarify non-functional requirements for timeout/performance"
        ));
        plan.setTestDataRequirements(Arrays.asList(
            new TestPlan.TestDataRequirement("Valid User", 3),
            new TestPlan.TestDataRequirement("Invalid User", 2)
        ));
        plan.setRationale("Fallback risk-based test plan generated locally");

        return plan;
    }

    private String fallbackPlannerJson(String artifactContent) {
        String ambiguity = artifactContent.toLowerCase().contains("tbd")
            ? "Artifact includes unresolved TBD sections"
            : "Timeout and performance constraints need clarification";

        return """
            {
              "riskAssessment": {
                "overallRisk": "HIGH",
                "justification": "Core flow and input validation are high impact",
                "riskAreas": [
                  {"area": "Core Functionality", "severity": "HIGH", "likelihood": "HIGH", "description": "Primary user journey"},
                  {"area": "Validation", "severity": "HIGH", "likelihood": "MEDIUM", "description": "Boundary and negative behavior"}
                ]
              },
              "testScenarios": [
                {"id": "TS-1", "title": "Happy path workflow", "description": "Valid input flow", "priority": "CRITICAL", "type": "HAPPY_PATH", "preconditions": ["Service is available"], "steps": ["Submit valid payload", "Verify success response"], "expectedResult": "Success response"},
                {"id": "TS-2", "title": "Boundary and negative behavior", "description": "Invalid and empty payloads", "priority": "HIGH", "type": "BOUNDARY", "preconditions": ["Service is available"], "steps": ["Submit invalid payload", "Verify validation error"], "expectedResult": "Error response"}
              ],
              "coverageAreas": [
                {"area": "Functional", "coveragePercent": 85, "scenariosCount": 2},
                {"area": "Validation", "coveragePercent": 80, "scenariosCount": 1}
              ],
              "ambiguities": [""" + quoteForJson(ambiguity) + """],
              "testDataRequirements": [
                {"entity": "Valid User", "quantity": 3},
                {"entity": "Invalid User", "quantity": 2}
              ],
              "entryCriteria": ["Environment available", "Artifact parsed"],
              "exitCriteria": ["Critical scenarios executed", "No blocker defects"],
              "rationale": "Risk-based coverage emphasizing critical and boundary paths"
            }
            """;
    }

    private static String quoteForJson(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
