package com.qeagent.agents;

import com.fasterxml.jackson.databind.JsonNode;
import com.qeagent.models.TestPlan;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;

/**
 * Stage 1: Convert artifact into risk-based test plan using LLM.
 */
public class TestPlannerAgent extends BaseAgent {
    private static final Logger logger = LoggerFactory.getLogger(TestPlannerAgent.class);

    public TestPlan generateTestPlan(String artifactContent, TestPlan.ArtifactType type) {
        String planId = "TP-" + UUID.randomUUID().toString().substring(0, 8);
        TestPlan plan = new TestPlan(planId, "Product Artifact", type);

        String systemPrompt = """
            You are a senior QA architect.
            Return only JSON with fields:
            riskAssessment, testScenarios, coverageAreas, ambiguities, testDataRequirements, entryCriteria, exitCriteria, rationale.
            Use high-value risk-based prioritization with meaningful negative and boundary cases.
            """;

        String userPrompt = "Artifact type: " + type + "\nArtifact content:\n" + artifactContent;

        String raw = invokeLlmOrFallback(
            "TestPlannerAgent",
            systemPrompt,
            userPrompt,
            () -> fallbackPlannerJson(artifactContent)
        );

        try {
            JsonNode root = MAPPER.readTree(raw);
            hydrateRisk(plan, readNode(root, "riskAssessment", "risk_assessment"));
            hydrateScenarios(plan, readNode(root, "testScenarios", "test_scenarios"));
            hydrateCoverage(plan, readNode(root, "coverageAreas", "coverage_areas"));
            hydrateDataRequirements(plan, readNode(root, "testDataRequirements", "test_data_requirements"));
            plan.setAmbiguities(readStringList(readNode(root, "ambiguities", "ambiguities")));
            plan.setEntryCriteria(readStringList(readNode(root, "entryCriteria", "entry_criteria")));
            plan.setExitCriteria(readStringList(readNode(root, "exitCriteria", "exit_criteria")));
            plan.setRationale(readText(root, "rationale", "rationale", "Risk-based plan generated by LLM"));
            enforceMinimumPlanQuality(plan, artifactContent);
        } catch (Exception ex) {
            logger.error("Planner parse failed; falling back to deterministic plan: {}", ex.getMessage());
            return buildFallbackPlan(planId, type, artifactContent);
        }

        logger.info("TestPlannerAgent: generated plan {} with {} scenarios", plan.getPlanId(), plan.getTestScenarios().size());
        return plan;
    }

    private void hydrateRisk(TestPlan plan, JsonNode node) {
        TestPlan.RiskAssessment assessment = new TestPlan.RiskAssessment();
        assessment.setOverallRisk(readText(node, "overallRisk", "overall_risk", "HIGH"));
        assessment.setJustification(readText(node, "justification", "justification", "Risk profile inferred from artifact"));

        List<TestPlan.RiskArea> areas = new ArrayList<>();
        for (JsonNode area : readArray(node, "riskAreas", "risk_areas")) {
            areas.add(new TestPlan.RiskArea(
                readText(area, "area", "component", "Core Functionality"),
                readText(area, "severity", "severity", "HIGH"),
                readText(area, "likelihood", "likelihood", "MEDIUM"),
                readText(area, "description", "description", "High-impact behavior"))
            );
        }

        if (areas.isEmpty()) {
            areas.add(new TestPlan.RiskArea("Core Functionality", "HIGH", "HIGH", "Primary business flow"));
        }

        assessment.setRiskAreas(areas);
        plan.setRiskAssessment(assessment);
    }

    private void hydrateScenarios(TestPlan plan, JsonNode scenariosNode) {
        List<TestPlan.TestScenario> scenarios = new ArrayList<>();
        int index = 1;
        for (JsonNode node : scenariosNode) {
            TestPlan.TestScenario s = new TestPlan.TestScenario();
            s.setId(node.path("id").asText("TS-" + index));
            s.setTitle(node.path("title").asText("Scenario " + index));
            s.setDescription(node.path("description").asText("Generated scenario"));
            s.setPriority(node.path("priority").asText("HIGH"));
            s.setType(node.path("type").asText("NEGATIVE"));
            for (String p : readStringList(node.path("preconditions"))) {
                s.getPreconditions().add(p);
            }
            for (String step : readStringList(node.path("steps"))) {
                s.getSteps().add(step);
            }
            s.setExpectedResult(readText(node, "expectedResult", "expected_result", "Expected behavior should match spec"));
            scenarios.add(s);
            index++;
        }

        if (scenarios.isEmpty()) {
            scenarios = buildFallbackPlan(plan.getPlanId(), plan.getArtifactType(), "").getTestScenarios();
        }
        plan.setTestScenarios(scenarios);
    }

    private void hydrateCoverage(TestPlan plan, JsonNode coverageNode) {
        List<TestPlan.CoverageArea> coverageAreas = new ArrayList<>();
        for (JsonNode node : readArray(coverageNode, "coverageAreas", "coverage_areas")) {
            coverageAreas.add(new TestPlan.CoverageArea(
                readText(node, "area", "name", "Functional"),
                readDouble(node, "coveragePercent", "coverage_percent", 80.0),
                readInt(node, "scenariosCount", "scenarios_count", Math.max(1, plan.getTestScenarios().size() / 2))
            ));
        }
        if (coverageAreas.isEmpty()) {
            coverageAreas.add(new TestPlan.CoverageArea("Functional", 85.0, Math.max(1, plan.getTestScenarios().size())));
        }
        plan.setCoverageAreas(coverageAreas);
    }

    private void hydrateDataRequirements(TestPlan plan, JsonNode dataNode) {
        List<TestPlan.TestDataRequirement> reqs = new ArrayList<>();
        for (JsonNode node : dataNode) {
            TestPlan.TestDataRequirement req = new TestPlan.TestDataRequirement(
                node.path("entity").asText(node.path("description").asText("Test Data")),
                node.path("quantity").asInt(3)
            );
            req.getAttributes().put("source", node.path("scenarioId").asText("general"));
            reqs.add(req);
        }

        if (reqs.isEmpty()) {
            reqs.add(new TestPlan.TestDataRequirement("Valid User", 3));
            reqs.add(new TestPlan.TestDataRequirement("Invalid User", 2));
        }
        plan.setTestDataRequirements(reqs);
    }

    private List<String> readStringList(JsonNode node) {
        List<String> values = new ArrayList<>();
        if (node.isArray()) {
            for (JsonNode item : node) {
                values.add(item.asText());
            }
        }
        return values;
    }

    private void enforceMinimumPlanQuality(TestPlan plan, String artifactContent) {
        int total = plan.getTestScenarios() == null ? 0 : plan.getTestScenarios().size();
        int negative = total == 0 ? 0 : countScenarioType(plan.getTestScenarios(), "NEGATIVE");
        int boundary = total == 0 ? 0 : countScenarioType(plan.getTestScenarios(), "BOUNDARY");

        boolean weakScenarioMix = total < 4 || negative == 0 || boundary == 0;
        boolean weakCoverage = plan.getCoverageAreas() == null || plan.getCoverageAreas().size() < 2;

        if (!weakScenarioMix && !weakCoverage) {
            return;
        }

        logger.warn("Planner output lacked minimum risk coverage (total={}, negative={}, boundary={}, coverageAreas={}); using deterministic fallback",
            total, negative, boundary, plan.getCoverageAreas() == null ? 0 : plan.getCoverageAreas().size());

        TestPlan fallback = buildFallbackPlan(plan.getPlanId(), plan.getArtifactType(), artifactContent);
        plan.setRiskAssessment(fallback.getRiskAssessment());
        plan.setTestScenarios(fallback.getTestScenarios());
        plan.setCoverageAreas(fallback.getCoverageAreas());
        plan.setTestDataRequirements(fallback.getTestDataRequirements());
        plan.setAmbiguities(fallback.getAmbiguities());
        plan.setEntryCriteria(fallback.getEntryCriteria());
        plan.setExitCriteria(fallback.getExitCriteria());
        plan.setRationale("LLM output was insufficient; " + fallback.getRationale());
    }

    private String readText(JsonNode node, String preferredKey, String fallbackKey, String defaultValue) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return defaultValue;
        }
        JsonNode preferred = node.path(preferredKey);
        if (!preferred.isMissingNode() && !preferred.isNull() && !preferred.asText().isBlank()) {
            return preferred.asText();
        }
        JsonNode fallback = node.path(fallbackKey);
        if (!fallback.isMissingNode() && !fallback.isNull() && !fallback.asText().isBlank()) {
            return fallback.asText();
        }
        return defaultValue;
    }

    private double readDouble(JsonNode node, String preferredKey, String fallbackKey, double defaultValue) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return defaultValue;
        }
        JsonNode preferred = node.path(preferredKey);
        if (!preferred.isMissingNode() && preferred.isNumber()) {
            return preferred.asDouble();
        }
        JsonNode fallback = node.path(fallbackKey);
        if (!fallback.isMissingNode() && fallback.isNumber()) {
            return fallback.asDouble();
        }
        return defaultValue;
    }

    private int readInt(JsonNode node, String preferredKey, String fallbackKey, int defaultValue) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return defaultValue;
        }
        JsonNode preferred = node.path(preferredKey);
        if (!preferred.isMissingNode() && preferred.isNumber()) {
            return preferred.asInt();
        }
        JsonNode fallback = node.path(fallbackKey);
        if (!fallback.isMissingNode() && fallback.isNumber()) {
            return fallback.asInt();
        }
        return defaultValue;
    }

    private Iterable<JsonNode> readArray(JsonNode node, String preferredKey, String fallbackKey) {
        JsonNode preferred = node.path(preferredKey);
        if (preferred.isArray()) {
            return preferred;
        }
        JsonNode fallback = node.path(fallbackKey);
        if (fallback.isArray()) {
            return fallback;
        }
        if (node.isArray()) {
            return node;
        }
        return new ArrayList<>();
    }

    private JsonNode readNode(JsonNode node, String preferredKey, String fallbackKey) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return MAPPER.nullNode();
        }
        JsonNode preferred = node.path(preferredKey);
        if (!preferred.isMissingNode() && !preferred.isNull()) {
            return preferred;
        }
        JsonNode fallback = node.path(fallbackKey);
        if (!fallback.isMissingNode() && !fallback.isNull()) {
            return fallback;
        }
        return MAPPER.nullNode();
    }

    private TestPlan buildFallbackPlan(String planId, TestPlan.ArtifactType type, String artifactContent) {
        TestPlan plan = new TestPlan(planId, "Product Artifact", type);
        String normalized = artifactContent == null ? "" : artifactContent.toLowerCase(Locale.ROOT);
        boolean userStoryStyle = normalized.contains("as a") && normalized.contains("i want");
        boolean hasApiSignals = normalized.contains("endpoint") || normalized.contains("http") || normalized.contains("request") || normalized.contains("response") || normalized.contains("status code");
        boolean hasSecuritySignals = normalized.contains("login") || normalized.contains("logged in") || normalized.contains("auth") || normalized.contains("token") || normalized.contains("permission") || normalized.contains("role");
        boolean hasBoundarySignals = normalized.contains("max") || normalized.contains("min") || normalized.contains("length") || normalized.contains("digits") || normalized.contains("characters") || normalized.contains("limit");

        TestPlan.RiskAssessment risk = new TestPlan.RiskAssessment();
        risk.setOverallRisk(hasSecuritySignals ? "CRITICAL" : "HIGH");
        risk.setJustification("Fallback deterministic plan built from artifact signals with risk-based positive, negative, and boundary coverage");
        List<TestPlan.RiskArea> riskAreas = new ArrayList<>();
        riskAreas.add(new TestPlan.RiskArea("Core Functionality", "HIGH", "HIGH", "Primary user journey and business flow"));
        riskAreas.add(new TestPlan.RiskArea("Validation", "HIGH", "MEDIUM", "Input validation, required checks, and invalid payload behavior"));
        if (hasBoundarySignals) {
            riskAreas.add(new TestPlan.RiskArea("Boundary Handling", "HIGH", "MEDIUM", "Min/max lengths, limits, and edge values"));
        }
        if (hasSecuritySignals) {
            riskAreas.add(new TestPlan.RiskArea("Security", "CRITICAL", "MEDIUM", "Authentication/authorization and token handling"));
        }
        if (hasApiSignals) {
            riskAreas.add(new TestPlan.RiskArea("API Contract", "HIGH", "MEDIUM", "Request/response schema and status-code correctness"));
        }
        risk.setRiskAreas(riskAreas);
        plan.setRiskAssessment(risk);

        List<TestPlan.TestScenario> scenarios = new ArrayList<>();
        int scenarioIndex = 1;

        scenarios.add(makeScenario(
            "TS-" + scenarioIndex++,
            userStoryStyle ? "User story happy path acceptance" : "Core workflow happy path",
            "Valid user input and expected successful outcome",
            "CRITICAL",
            "HAPPY_PATH",
            Arrays.asList("Service is available", "Dependencies are healthy"),
            Arrays.asList("Submit valid payload", "Verify successful response and persisted state"),
            "System returns success and persists expected values"
        ));

        scenarios.add(makeScenario(
            "TS-" + scenarioIndex++,
            "Required-field negative validation",
            "Ensure mandatory inputs are enforced",
            "HIGH",
            "NEGATIVE",
            Arrays.asList("Service is available"),
            Arrays.asList("Submit payload with one or more required fields missing", "Validate structured error response"),
            "System rejects request with clear required-field validation errors"
        ));

        Set<String> extractedFields = extractFieldCandidates(artifactContent);
        for (String field : extractedFields) {
            if (scenarios.size() >= 10) {
                break;
            }

            String lowered = field.toLowerCase(Locale.ROOT);
            if (lowered.contains("email") || lowered.contains("phone") || lowered.contains("password") || lowered.contains("name")) {
                scenarios.add(makeScenario(
                    "TS-" + scenarioIndex++,
                    field + " format validation",
                    "Validate both valid and invalid formats for " + field,
                    "HIGH",
                    "NEGATIVE",
                    Arrays.asList("Validation rules configured"),
                    Arrays.asList("Submit valid " + field + " value", "Submit malformed " + field + " value", "Compare validation responses"),
                    "Valid value is accepted and malformed value is rejected"
                ));
            }
        }

        if (hasBoundarySignals || !extractedFields.isEmpty()) {
            scenarios.add(makeScenario(
                "TS-" + scenarioIndex++,
                "Boundary value coverage",
                "Check min/max and edge-case values",
                "HIGH",
                "BOUNDARY",
                Arrays.asList("Validation constraints identified"),
                Arrays.asList("Submit payload at min boundary", "Submit payload at max boundary", "Submit payload outside boundaries"),
                "Boundary values pass and out-of-range values are rejected"
            ));
        }

        if (hasSecuritySignals) {
            scenarios.add(makeScenario(
                "TS-" + scenarioIndex++,
                "Authorization and token security",
                "Verify unauthorized access is blocked",
                "CRITICAL",
                "SECURITY",
                Arrays.asList("Protected endpoint configured"),
                Arrays.asList("Call endpoint without token", "Call endpoint with invalid/expired token", "Call endpoint with valid token"),
                "Unauthorized calls fail with 401/403 while valid token succeeds"
            ));
        }

        if (hasApiSignals) {
            scenarios.add(makeScenario(
                "TS-" + scenarioIndex++,
                "API contract and status-code validation",
                "Ensure response schema and status codes match spec",
                "HIGH",
                "NEGATIVE",
                Arrays.asList("API spec available"),
                Arrays.asList("Send valid request", "Send malformed request", "Verify response schema and status codes"),
                "Contract-compliant responses are returned for success and failure paths"
            ));
        }

        plan.setTestScenarios(scenarios);

        int happy = countScenarioType(scenarios, "HAPPY_PATH");
        int negative = countScenarioType(scenarios, "NEGATIVE");
        int boundary = countScenarioType(scenarios, "BOUNDARY");
        int security = countScenarioType(scenarios, "SECURITY");

        List<TestPlan.CoverageArea> coverageAreas = new ArrayList<>();
        coverageAreas.add(new TestPlan.CoverageArea("Functional", 90.0, happy));
        coverageAreas.add(new TestPlan.CoverageArea("Negative", 88.0, negative));
        coverageAreas.add(new TestPlan.CoverageArea("Boundary", boundary > 0 ? 85.0 : 70.0, Math.max(1, boundary)));
        if (security > 0) {
            coverageAreas.add(new TestPlan.CoverageArea("Security", 84.0, security));
        }
        plan.setCoverageAreas(coverageAreas);

        plan.setEntryCriteria(Arrays.asList("Environment available", "Artifact parsed"));
        plan.setExitCriteria(Arrays.asList(
            "All critical and high-priority scenarios executed",
            "Positive, negative, and boundary suites completed",
            "No unresolved blocker defects"
        ));

        List<String> ambiguities = new ArrayList<>();
        if (normalized.contains("tbd")) {
            ambiguities.add("Artifact includes TBD sections requiring clarification.");
        }
        if (userStoryStyle && !(normalized.contains("acceptance criteria") || normalized.contains("given") || normalized.contains("when") || normalized.contains("then"))) {
            ambiguities.add("User story lacks explicit acceptance criteria (Given/When/Then). Please confirm expected outcomes.");
        }
        if (ambiguities.isEmpty()) {
            ambiguities.add("Clarify non-functional thresholds (latency, scale, and timeout expectations).");
        }
        plan.setAmbiguities(ambiguities);

        plan.setTestDataRequirements(Arrays.asList(
            new TestPlan.TestDataRequirement("Valid payload samples", 5),
            new TestPlan.TestDataRequirement("Invalid/negative payload samples", 5),
            new TestPlan.TestDataRequirement("Boundary-value payload samples", 4)
        ));
        plan.setRationale(String.format(
            "Fallback risk-based test plan generated locally with %d scenarios (%d happy, %d negative, %d boundary%s).",
            scenarios.size(),
            happy,
            negative,
            boundary,
            security > 0 ? ", security" : ""
        ));

        return plan;
    }

    private String fallbackPlannerJson(String artifactContent) {
        try {
            TestPlan.ArtifactType inferredType = inferArtifactType(artifactContent);
            TestPlan fallback = buildFallbackPlan("TP-FALLBACK", inferredType, artifactContent);
            return MAPPER.writeValueAsString(new PlannerFallbackEnvelope(fallback));
        } catch (Exception ex) {
            return "{\"riskAssessment\":{\"overallRisk\":\"HIGH\"},\"testScenarios\":[],\"coverageAreas\":[],\"ambiguities\":[\"Failed to build fallback plan\"],\"testDataRequirements\":[],\"entryCriteria\":[],\"exitCriteria\":[],\"rationale\":\"Fallback serialization failed\"}";
        }
    }

    private TestPlan.TestScenario makeScenario(String id,
                                               String title,
                                               String description,
                                               String priority,
                                               String type,
                                               List<String> preconditions,
                                               List<String> steps,
                                               String expectedResult) {
        TestPlan.TestScenario scenario = new TestPlan.TestScenario();
        scenario.setId(id);
        scenario.setTitle(title);
        scenario.setDescription(description);
        scenario.setPriority(priority);
        scenario.setType(type);
        scenario.getPreconditions().addAll(preconditions);
        scenario.getSteps().addAll(steps);
        scenario.setExpectedResult(expectedResult);
        return scenario;
    }

    private int countScenarioType(List<TestPlan.TestScenario> scenarios, String type) {
        int count = 0;
        for (TestPlan.TestScenario scenario : scenarios) {
            if (type.equalsIgnoreCase(scenario.getType())) {
                count++;
            }
        }
        return count;
    }

    private Set<String> extractFieldCandidates(String artifactContent) {
        Set<String> fields = new LinkedHashSet<>();
        if (artifactContent == null) {
            return fields;
        }

        String[] lines = artifactContent.split("\\r?\\n");
        for (String rawLine : lines) {
            String line = rawLine.trim();
            if (line.isEmpty()) {
                continue;
            }

            String cleaned = line.replaceFirst("^[-*•]\\s*", "");
            if (cleaned.contains(":")) {
                String candidate = cleaned.substring(0, cleaned.indexOf(':')).trim();
                if (isFieldName(candidate)) {
                    fields.add(candidate);
                }
            }

            String lower = cleaned.toLowerCase(Locale.ROOT);
            if (lower.contains("email")) fields.add("email");
            if (lower.contains("phone")) fields.add("phoneNumber");
            if (lower.contains("password")) fields.add("password");
            if (lower.contains("name")) fields.add("name");
            if (lower.contains("address")) fields.add("address");
        }
        return fields;
    }

    private boolean isFieldName(String candidate) {
        if (candidate == null || candidate.isBlank()) {
            return false;
        }
        String normalized = candidate.toLowerCase(Locale.ROOT);
        if (normalized.length() > 30) {
            return false;
        }
        return !(normalized.contains("when") || normalized.contains("then") || normalized.contains("given")
            || normalized.contains("acceptance") || normalized.contains("scenario") || normalized.contains("story"));
    }

    private TestPlan.ArtifactType inferArtifactType(String artifactContent) {
        String normalized = artifactContent == null ? "" : artifactContent.toLowerCase(Locale.ROOT);
        if (normalized.contains("as a") && normalized.contains("i want") && normalized.contains("so that")) {
            return TestPlan.ArtifactType.USER_STORY;
        }
        if (normalized.contains("endpoint") || normalized.contains("request") || normalized.contains("response") || normalized.contains("status code")) {
            return TestPlan.ArtifactType.API_SPEC;
        }
        return TestPlan.ArtifactType.PRD;
    }

    private static final class PlannerFallbackEnvelope {
        public final TestPlan.RiskAssessment riskAssessment;
        public final List<TestPlan.TestScenario> testScenarios;
        public final List<TestPlan.CoverageArea> coverageAreas;
        public final List<String> ambiguities;
        public final List<TestPlan.TestDataRequirement> testDataRequirements;
        public final List<String> entryCriteria;
        public final List<String> exitCriteria;
        public final String rationale;

        private PlannerFallbackEnvelope(TestPlan plan) {
            this.riskAssessment = plan.getRiskAssessment();
            this.testScenarios = plan.getTestScenarios();
            this.coverageAreas = plan.getCoverageAreas();
            this.ambiguities = plan.getAmbiguities();
            this.testDataRequirements = plan.getTestDataRequirements();
            this.entryCriteria = plan.getEntryCriteria();
            this.exitCriteria = plan.getExitCriteria();
            this.rationale = plan.getRationale();
        }
    }

    private static String quoteForJson(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
